# Generated by Django 4.0 on 2022-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0002_rename_last_update_activities_last_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tasks_types',
            field=models.CharField(choices=[('single_task', 'Single Task'), ('daily_routine', 'Daily Routine'), ('long_term_goal', 'Long Term Goal')], default='single_task', max_length=255),
        ),
    ]
