# Generated by Django 4.0 on 2022-02-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0005_alter_meetings_points_related_contributor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings_points',
            name='point_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetings_points',
            name='priority_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.priorities'),
        ),
    ]
