# Generated by Django 4.0 on 2022-02-06 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='completion_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Completion Status',
                'verbose_name_plural': 'Completion Statuses',
            },
        ),
        migrations.CreateModel(
            name='contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.clients')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='point_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('sort_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point Type',
                'verbose_name_plural': 'Point Types',
            },
        ),
        migrations.CreateModel(
            name='priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.clients')),
                ('focal_person_contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('business_value', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.activities')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.clients')),
                ('completed_by_contibutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
                ('completion_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.completion_statuses')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.projects')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='plans_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_remarks', models.CharField(max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('assigned_to_contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
                ('completion_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.completion_statuses')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.plans')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.priorities')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.tasks')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Plans Tasks',
            },
        ),
        migrations.CreateModel(
            name='meetings_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.meetings')),
                ('point_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.point_types')),
                ('related_contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
            ],
            options={
                'verbose_name': 'Meeting Point',
                'verbose_name_plural': 'Meetings Points',
            },
        ),
        migrations.CreateModel(
            name='meetings_attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.meetings')),
            ],
            options={
                'verbose_name': 'Meeting Attendee',
                'verbose_name_plural': 'Meetings Attendees',
            },
        ),
        migrations.AddField(
            model_name='meetings',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.projects'),
        ),
        migrations.CreateModel(
            name='contributors_performance_scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.activities')),
                ('contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors')),
            ],
            options={
                'verbose_name': 'Performance Score',
                'verbose_name_plural': 'Performance Scores',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='owner_contributor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
    ]
