# Generated by Django 4.0 on 2022-02-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='completion_statuses',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='contributors_performance_scores',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='meetings_attendees',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='meetings_points',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='plans_tasks',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='point_types',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='priorities',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='last_update',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='last_update',
            new_name='last_update_date',
        ),
    ]
