# Generated by Django 4.0 on 2022-02-06 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0003_tasks_tasks_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='email_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contributors_performance_scores',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.clients'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.projects'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='title',
            field=models.CharField(default='Catch up', max_length=255),
        ),
        migrations.AlterField(
            model_name='meetings_attendees',
            name='contributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='meetings_points',
            name='related_contributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='period_end',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='plans_tasks',
            name='assigned_to_contributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='plans_tasks',
            name='completion_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.completion_statuses'),
        ),
        migrations.AlterField(
            model_name='plans_tasks',
            name='retro_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='focal_person_contributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='activity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.activities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='business_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.clients'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_by_contibutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.projects'),
        ),
    ]
