# Generated by Django 4.0 on 2022-02-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0006_meetings_points_point_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='task_id',
            field=models.ManyToManyField(to='itask.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='activity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.activities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='business_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.clients'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_by_contibutor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.projects'),
        ),
    ]
