# Generated by Django 4.0 on 2022-02-13 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0008_remove_plans_tasks_assigned_to_contributor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='activity_id',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.activities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to_contributor_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_contributor_id', to='itask.contributors'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='business_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='client_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.clients'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completion_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itask.completion_statuses'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Planning Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='To be defined', max_length=1500, verbose_name='Task title'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='itask.priorities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.projects'),
        ),
    ]
