# Generated by Django 4.0 on 2022-02-27 01:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0009_alter_tasks_activity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_interview_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Interview Question',
                'verbose_name_plural': 'Default Interview Questions',
            },
        ),
        migrations.CreateModel(
            name='interview_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_email', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_applied', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_location', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('interview_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview_status', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_score', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.clients')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itask.projects')),
            ],
        ),
        migrations.CreateModel(
            name='interview_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.interview_notes')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
            },
        ),
    ]
