# Generated by Django 4.0 on 2022-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0010_default_interview_questions_interview_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview_notes',
            options={'verbose_name': 'Interview Note', 'verbose_name_plural': 'Interview Notes'},
        ),
        migrations.AlterField(
            model_name='interview_notes',
            name='candidate_resume',
            field=models.FileField(blank=True, null=True, upload_to='itask/resumes/'),
        ),
        migrations.AlterField(
            model_name='interview_notes',
            name='designation_applied',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='routines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_details', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.activities')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
            },
        ),
    ]
