# Generated by Django 4.0 on 2022-08-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itask', '0011_alter_interview_notes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_routine_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_details', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itask.activities')),
            ],
            options={
                'verbose_name': 'Temptable',
                'verbose_name_plural': 'Temptable',
            },
        ),
    ]
