# Generated by Django 4.0 on 2022-08-10 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbit_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushup_logs',
            options={'verbose_name': 'Pushup Log', 'verbose_name_plural': 'Pushup Logs'},
        ),
        migrations.AlterField(
            model_name='pushup_logs',
            name='exercize_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
